FROM node:22

WORKDIR /usr/src/app

COPY . .

ENV PORT=8000
ENV DATABASE_TYPE=mysql
ENV DATABASE_HOST=mysql
ENV DATABASE_PORT=3306
ENV DATABASE_USERNAME=chanyut
ENV DATABASE_PASSWORD=chanyut.281144
ENV DATABASE_NAME=order_system

ENV SECRET_KEY=UFrIVWBPRW0HRLtuljpG1kdLSAFAcQOX
ENV SECRET_REFRESH_KEY=vDE7opAO6IrNW9ia5MxAFqHFk17MaRF0
ENV ALGORITHM=HS256
ENV AUDIENCE=my-app
ENV ISSUER=my-app
ENV EXPIRES_IN_ACCESS=1d
ENV EXPIRES_IN_REFRESH=7d

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

RUN npm install --legacy-peer-deps

CMD [ "npm", "run", "start:dev" ]